[package]
name = "longest-palindromic-substring"
version = "1.0.1"
authors = ["miRoox <miroox@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
