name: C++
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: "11"
      - name: Build
        env:
          CC: clang-11
          CXX: clang++-11
        run: |
          cmake ..
          cmake --build .
        working-directory: cpp/build
      - name: Test
        run: ctest -C Debug -VV
        working-directory: cpp/build
