name: Rust
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: xd009642/tarpaulin
      options: --security-opt seccomp=unconfined
    steps:
      - uses: actions/checkout@v2
      - name: Install Rustfmt
        run: rustup component add rustfmt
      - name: Build
        run: cargo build --workspace --verbose
        working-directory: rust
      - name: Test
        run: cargo tarpaulin --verbose --workspace --timeout 120 --out Xml
        working-directory: rust
      - name: Format
        run: cargo fmt --all -- --check
        working-directory: rust
      - name: Codecov
        uses: codecov/codecov-action@v2
