name: Test
on: [push, pull_request]

jobs:
  cpp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          cmake ..
          cmake --build .
        working-directory: cpp/build
      - name: Test
        run: ctest -C Debug -VV
        working-directory: cpp/build
  rust:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - name: Build
        run: cargo build --workspace --verbose
        working-directory: rust
      - name: Test
        run: cargo test --workspace --verbose
        working-directory: rust
      - name: Format
        run: cargo fmt --all -- --check
        working-directory: rust
