name: Test
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup rust
        uses: dtolnay/rust-toolchain@master
      - name: Build
        run: |
          cd build
          cmake ..
          cmake --build.
      - name: Test
        run: ctest --build-config Debug -VV
